FROM node:6.9.5-alpine
RUN mkdir -p /opt/voyager
WORKDIR /opt/voyager
COPY voyager /opt/voyager

RUN npm install -g -s --no-progress yarn && \
    yarn && \
    yarn run build
#    yarn run prune && \
#    yarn cache clean
CMD [ "yarn", "start" ]
EXPOSE 3000
